name: Update upstream content

on: 
  workflow_dispatch:
    inputs:
      ref:
        description: 'Reference to sync from'
        required: false
        default: 'main'

jobs:
  update:
    name: Run update
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Update from upstream repo
        id: sync_upstreams
        uses: RedHatProductSecurity/trestle-bot/actions/sync-upstreams@main
        with:
          branch: "sync-upstream-${{ github.run_id }}"
          target_branch: "main"
          commit_message: "Updates content from trestlebot-demo-cd repository"
          pull_request_title: "Updates content from trestlebot-demo-cd repository"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sources: |
            https://github.com/RedHatProductSecurity/oscal-profiles@main